### ISSUE TITLE
Enlisting Function - Homework Q.5

### ISSUE THREAD

**Issue by sderrett** [Pierian-Data/Complete-Python-3-Bootcamp#101]
Hello,

I was just wondering for the Functions and Methods homework assignment question 5 - multiply all the numbers in a list - are the square brackets used to turn 'numbers' into a list with an unknown number of variables?
e.g.

def multiply(numbers):
          total = numbers[0]       <----- I don't quite get this bit - why [0]?
          for x in numbers:
                  total *=x
          return total

Thanks so much for your help!

**Comment by murphygreen8484** [comment]
Putting values in square brackets makes them a list. If you pass in a list you can do list comprehension like mysum = [sum(x) for x in numbers]

I can look for the exact code on break if you need, but I know I used the list comprehension

**Comment by murphygreen8484** [comment]
Just looked at my code. Sorry, no brackets needed. Just pass in a touple and use *args so you can pass in as many as you need:

def multval(*args):
    totval = 1
    for x in args:
        totval *= x
    return totval

**Comment by sderrett** [comment]
Okay, so you can either do a list comprehension or use *args?

Thanks for your help!
