### ISSUE TITLE
Global example from slide

### ISSUE THREAD

**Issue by sderrett** [Pierian-Data/Complete-Python-3-Bootcamp#102]
I had a question about the slide in the course that mentions the global function. The example was like this:

x = 50

def func(x):
       print (f'X is {x}')
        # local reassignment!
        x = 200
       print (f'I just locally changed x to {x}')

func(x)
--> X is 50
I just locally changed x to 200.

print(x)
--> 50

I totally get all of this. What happens next confuses me, when the global function is added.

x = 50

def func(x):
        global x                 <------ shouldn't this be overwriting x as 200 everywhere?
       print (f'X is {x}')
        # local reassignment!
        x = 200
       print (f'I just locally changed x to {x}')

func(x)
--> X is 50           <------ so this should be 200? Why is it still 50?
I just locally changed x to 200.

print(x)
--> 200            <------- and this should also be 200?

Hope that's clear! Thank you so much!

**Comment by murphygreen8484** [comment]
I haven't gotten to that section yet of the class. As soon as I do though I will take a look at this and let you know. Thank you.

**Comment by kkunal97** [comment]
please let me know in brief i am not able to get how is it  changed to 200
