### ISSUE TITLE
Summer of '69 exercise faster solution

### ISSUE THREAD

**Issue by realleoman** [Pierian-Data/Complete-Python-3-Bootcamp#110]
In the 03-Function Practice Exercises.ipynb notebook, Summer f '69 exercise, the instructor posted a long solution as an answer.

**Wouldn't it be better to follow this approach instead?**

```
def summer_69(arr):
    if (6 not in arr):
        print(0)
    else:
        print(sum((arr[0:arr.index(6)])+(arr[arr.index(9)+1:])))
```

**Comment by ramesh-1980** [comment]
can you put some explanation of the code . it is quite complicated to understand  the code

**Comment by mahisafa82** [comment]
No It's not working [1,4,7,**6**,43,8,**9**,1,2,**6**,7,2,5,2,5,2,5,**9**]

**Comment by rajnishgiet** [comment]
def summer_69(arr):
    start = 6
    startidx = 0
    end = 9
    endidx = 0
 
    for i in range(len(arr)):
        if arr[i] == start:
            startidx = i 
            while arr[i] != end:
                i+=1 #While value not 9, iterate i
            endidx = i+1
            arr[startidx:endidx] = [0 for x in arr[startidx:endidx]]
    return sum(arr)

**Comment by RahulRajdkp** [comment]
https://codereview.stackexchange.com/questions/225266/python-implementation-summer-of-69

User oladayo  posted :

def summer_69(arr):
     if len(arr)==0:    #checking if array is empty or not
        return 0
    elif 6 in arr:         # if 6 , subracts the sum from values  between  6 till 9 
        return sum(arr) - sum(arr[arr.index(6):arr.index(9)+1])       # arr[ start :end +1]
    else:
        return sum(arr)
    pass

**Comment by jejkujejku** [comment]
def summer_69(*arr):
    j=0
    if arr.count(6)>0:
        if arr.count(9)>0:
            for i in arr: 
                if i<6 or i>9:
                    j=i+j
        else:
            j=i+j   
    return j

summer_69(1,3,5,6,7,8,9,11,12,13)
