### ISSUE TITLE
can't write code

### ISSUE THREAD

**Issue by chris12252006** [Pierian-Data/Complete-Python-3-Bootcamp#118]
I am struggling tiwrite the code down it won't allow me to write anything

**Comment by datttran** [comment]
Did you open it on Jupiter Notebook? Post some screenshots so we know what happen.

**Comment by chinmay-stack** [comment]
did i have to download jupiter notebook? is it necessary

**Comment by datttran** [comment]
if you want to do the hw then yes, you will need jupiter. It, however, come along with anaconda. So if you followed the tut, you already had it. just run jupiter notebook and open the hw file you got from github.
