### ISSUE TITLE
trying to understand logic

### ISSUE THREAD

**Issue by Archana9814** [Pierian-Data/Complete-Python-3-Bootcamp#120]
this is level 2 problems from function exercise
Given a list of ints, return True if the array contains a 3 next to a 3 somewhere.
sol:
def has_33(nums):
    for x in range(0,len(nums)-1):
        if nums[x:x+2] == [3,3]:
            return True
    else:
        return False

here, we want to find array contains 3 next to 3.
in slicing we need to put nums[x:x+1]
I think we need to check next position so we need to use x:x+1
but we are using x:x+2
please help me understanding this

**Comment by VigneshSahoo** [comment]
@Archana9814 , 
It's an alternate way.  You can go ahead and find it using the method which is commented (#)
And if you notice, there is a colon between x and x + 2 in **nums[x:x+2]**. So, you are selecting values from x till x + 2 which means x and x + 1. 
For Example:
list1 = [0, 1, 2, 3, 4, 5]
print(list1[1:4])
output = [1, 2, 3]
I hope you got it now. If not, please go through the list topic again or you can ask your queries here..

**Comment by Archana9814** [comment]
Thank you so much for quick response. I got it now.
Thank you so much

**Comment by gopikagopikrishnan** [comment]
Given a list of ints, return True if the array contains a 3 next to a 3 somewhere.

    has_33([1, 3, 3]) → True
    has_33([1, 3, 1, 3]) → False
    has_33([3, 1, 3]) → False
### For this exercise,is the below solution correct?Because the outputs are correct when I run it.

def has_33(nums):
    for num in nums:
        if nums[0] == nums [1] == 3 or nums[1] == nums[2] == 3:
            return True
        else:
            return False
