### ISSUE TITLE
Unable to write the code

### ISSUE THREAD

**Issue by AdityaSinghai** [Pierian-Data/Complete-Python-3-Bootcamp#121]
I am unable to write the code.How do I redirect it to Jupyter notebook?

**Comment by datttran** [comment]
Did you download the zip file, unzip it and then open it in Jupyter notebook? Need more details about what you meant by “unable to write the code”.

**Comment by Lomors** [comment]
Sorry? I didn't report any issue.

**Comment by chinmay-stack** [comment]
how to unzip the file
