### ISSUE TITLE
Error on File I/O

### ISSUE THREAD

**Issue by srskaku** [Pierian-Data/Complete-Python-3-Bootcamp#123]
i get this error 
%%UsageError: %%writefile is a cell magic, but the cell body is empty.
while i am writing a code of  : %%writefile test.txt

**Comment by RAHULRAOSHINDE** [comment]
TRY BY WRITING SOME TEXT IN NEXT LINE OF THE SAME CELL 
%%writefile test.txt
Coding iin Python
