### ISSUE TITLE
SPY GAME: Write a function that takes in a list of integers and returns True if it contains 007 in order.

### ISSUE THREAD

**Issue by karthikkunala** [Pierian-Data/Complete-Python-3-Bootcamp#127]
SPY GAME: Write a function that takes in a list of integers and returns True if it contains 007 in order.

For this one, the entire solution is wrong because what is asked in question is a number that appears continuously 007 but in actual case its showing True for 50307 and also for53007. There must be some modification done to the solution.

**Comment by codegh0st** [comment]
No code is fine, its said in order means. First 0 should come, then again a 0, then a 7. 

Eg. 50307- its has same thing- after 1st '0' , there is again a '0', then there is '7'  so its true. Don't care about how many interger fall in between these 0xxx0xx7xxx. All you have to check if it is in 007 form or not. 
 If 0xx7x0- false. 
If xx7x00x false. 
If 50307 true. 
   50730 false. 
   57300 false   
Try understand. Thank you.

**Comment by dustinpeng** [comment]
agree. but I have the same understanding at first with karthikkunala
