### ISSUE TITLE
Learn Python using Android Phone Make Twenty fuction. 

### ISSUE THREAD

**Issue by codegh0st** [Pierian-Data/Complete-Python-3-Bootcamp#131]
![Screenshot_2020-04-06-14-43-02-717_ru iiec pydroid3](https://user-images.githubusercontent.com/63223838/78542743-40800700-7815-11ea-915d-f8954a51ea14.png)

**Comment by codegh0st** [comment]
I'm beginner in programing.

**Comment by chaitanya1212** [comment]
10
