### ISSUE TITLE
Kernels STILL Disconnecting...

### ISSUE THREAD

**Issue by ThomasKirkatrick** [Pierian-Data/Complete-Python-3-Bootcamp#15]
I have been asking for assistance on my local kernel disconnecting for the past month. I am attempting to finish my certificate with the Udemy Python 3 course Zero to Hero. It seems when I run input functions ex:        

def play_game():
    
      start_game = str(input("Ready..? Yes or No: ")).

A hourglass appears next to my Jupyter notebook. After I cannot run any code. The only solution I have found is to restart the kernel, but short thereafter if I run my input functions it occurs again. This is a very frustrating issue that has set me back a couple weeks from my anticipated end date for my Udemy course. I have no got any reliable feedback and would greatly appreciate some help with issue.

Thanks,

Thomas

**Comment by Pierian-Data** [comment]
Hello,
Please post questions to the QA forum with the entirety of your code (or just link to your notebook hosted on github).

**Comment by ThomasKirkatrick** [comment]
import random

suits = ('Hearts', 'Diamonds', 'Spades', 'Clubs')
ranks = ('Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King', 'Ace')
values = {'Two':2, 'Three':3, 'Four':4, 'Five':5, 'Six':6, 'Seven':7, 'Eight':8, 'Nine':9, 'Ten':10, 'Jack':10,
         'Queen':10, 'King':10, 'Ace':11}

playing = True

**Comment by ThomasKirkatrick** [comment]
class Card():
    
    def __init__(self,suit,rank):
        self.suit = suit
        self.rank = rank
    
    def __str__(self):
        return self.rank+ " of "+self.suit

**Comment by ThomasKirkatrick** [comment]
class Deck:
    
    def __init__(self):
        self.deck = []  # start with an empty list
        for suit in suits:
            for rank in ranks:
                self.deck.append(Card(suit,rank))
    
    def __str__(self):
        deck_comp = ''
        for card in self.deck:
            deck_comp += '\n'+ card.__str__()
        return "The deck has: "+deck_comp

    def shuffle(self):
        random.shuffle(self.deck)
        
    def deal(self):
        single_card = self.deck.pop()
        return single_card

**Comment by ThomasKirkatrick** [comment]
class Hand:
    def __init__(self):
        self.cards = []
        self.value = 0
        self.aces = 0
    
    def add_card(self,card):
        self.cards.append(card)
        self.value += values[card.rank]
        
        # Track aces
        if card.rank == 'Ace':
            self.aces += 1
        
    def adjust_for_ace(self):
        
        # IF TOTAL VALUE > 21 AND I STILL HAVE AN ACE
        # THAN CHANGE MY ACE TO BE A 1 INSTEAD OF AN 11
        while self.value > 21 and self.aces > 0:
            self.value -= 10
            self.aces -= 1

**Comment by ThomasKirkatrick** [comment]
class Chips:
    def __init__(self,total=100):
        self.total = total # This can be set to a default value
        self.bet = 0
        
    def win_bet(self):
        self.total += self.bet
        
    def lose_bet(self):
        self.total -= self.bet

**Comment by ThomasKirkatrick** [comment]
def take_bet(chips):
    
    while True:
        
        try:
            chips.bet = int(input("How many chips would you like to bet? "))
        except:
            print("Sorry please provide an integer")
        else:
            if chips.bet > chips.total:
                print('Sorry, you do not have enough chips! You have {}'.format(chips.total))
            else:
                break

**Comment by ThomasKirkatrick** [comment]
def hit(deck,hand):
    
    single_card = deck.deal()
    hand.add_card(single_card)
    hand.adjust_for_ace()

**Comment by ThomasKirkatrick** [comment]
def hit_or_stand(deck,hand):
    global playing
    
    while True:
        x = input("hit or Stand? Enter h or s ")
        
        if x[0].lower == 'h':
            hit(deck,hand)
        
        elif x [0].lower() == 's':
            print("Player Stands Dealer's Turn")
            playing = False
        
        else:
            print("I am confused, do you want to hit or stay")

**Comment by ThomasKirkatrick** [comment]
def player_busts(player,dealer,chips):
    print("Bust Player")
    chips.lose_bet()

def player_wins(player,dealer,chips):
    print("Player Wins!!")
    chips.win_bet()

def dealer_busts(player,dealer,chips):
    print("Player Wins!")
    chps.win_bet()

def dealer_wins(player,dealer,chips):
    print("Dealer wins")
    chips.lose_bet()

def push(player,dealer,chips):
    print("Dealer and player TIE! PUSH")

**Comment by Pierian-Data** [comment]
Hi,
This is not the correct area for assistance, we're happy to help you out, but you need to post to the right location, this it the github issues page, not the QA (Question Answer) Forum for the course. The teaching assistants and I can't effectively help you here. Please do the following:

1. Go to the course Q&A Forum.
2. Post a screenshot of your error.
3. Post a link to your notebook (.ipynb) file. You can create a repo and just upload the single .ipynb file.
4. Then we can effectively help you.

Thanks.
