### ISSUE TITLE
Repositories not loading

### ISSUE THREAD

**Issue by greenteaisgreat** [Pierian-Data/Complete-Python-3-Bootcamp#157]
I'm unable to open any of the repositories; the .ipynb files will load with raw text, but the easier to read rendered version isn't opening, on any of the lecture notes. I keep hitting the reload button when it says "Something went wrong. Reload?", but that's not fixing the issue. What's up with that? I'm on desktop, wishing to view the notes from my browser (Chrome), rather than opening up the .ipynb file in Jupyter.

![bug](https://user-images.githubusercontent.com/49956464/82127552-1148a800-977a-11ea-9679-87fa4c5e505c.png)

**Comment by prodigy1284** [comment]
I'm experiencing this same problem. How can this be fixed?

**Comment by benjaminpierson** [comment]
Same here

**Comment by jtgeorge800** [comment]
Me as well

**Comment by jtgeorge800** [comment]
I figured it out. If you are using the desktop version...go to your browser and type in www.github.com/<your username>/<folder containing repository>

After that it will take you to the github website, only it will have a Quick Setup in bold at the top. From there, you have the option of clicking the button to Setup On Desktop, or if you look to the right you will see a url to the repository with YOUR name and folder in it Just use that URL and it should take you to the Web version of the notes and it should open just fine. Good luck

**Comment by benjaminpierson** [comment]
Thank you sir
