### ISSUE TITLE
Can't type code

### ISSUE THREAD

**Issue by Minibumphead** [Pierian-Data/Complete-Python-3-Bootcamp#172]
I can't seem to type any code into the cells. What might the issue be?

**Comment by khanamir1974** [comment]
I am experiencing the same issue

**Comment by Minibumphead** [comment]
Are you supposed to be able to do it on GitHub or do you have to like
download the assignment? I’m confused

**Comment by ItIsAndrewL** [comment]
You have to download the assignments on your computer to type in the boxes.

The easiest thing to do is to download the file from the code page.  There should be a green "clone or download" button.  Click that then "download zip" and all the assignments should download.  Unzip and load it up in the Jupyter notebook (which is part of the anaconda installer).
