### ISSUE TITLE
Notebook, structure vs course structure has diverged

### ISSUE THREAD

**Issue by WinstonN** [Pierian-Data/Complete-Python-3-Bootcamp#179]
I am on this section
```
Functions #8 *args
```
I answer the question (Coding Exercise 17: functions #8 *arg) as
```
def myfunc(*args)
    return sum(args)
```
This fails. I want to check the work book, and this is where the structure seems mixed up. This makes it incredibly difficult to quickly see what it is that you expect as an answer - not really helpful.

**Comment by Pierian-Data** [comment]
Please make sure to read the article lecture before the coding exercises. The in-course coding exercises from Udemy are not notebook based, so the solutions were linked in the article lecture before the exercises.
