### ISSUE TITLE
ipywidgets widgets not displaying

### ISSUE THREAD

**Issue by cfwalton5152** [Pierian-Data/Complete-Python-3-Bootcamp#18]
Hi,

For some reason, I can't get the widgets to display. Below is a screenshot I took that shows interact() not working. Is there a bug with ipywidgets? Thanks for your help!

![no_slider](https://user-images.githubusercontent.com/34494201/40287532-18eccede-5c6b-11e8-8c6e-29a72e48691c.PNG)

**Comment by Pierian-Data** [comment]
Best place to ask questions is in Udemy QA forums. Thanks!
