### ISSUE TITLE
why the code doesn't work

### ISSUE THREAD

**Issue by younghope11** [Pierian-Data/Complete-Python-3-Bootcamp#186]
I write the following codes, however it always ask me to enter the value without judgement. Can anyone tell me why?Thanks. 
<img width="1123" alt="Screen Shot 2020-06-30 at 13 59 27" src="https://user-images.githubusercontent.com/48189710/86089013-fb006c80-bad9-11ea-8f96-07c9523392ab.png">

**Comment by rohitsinghkcodes** [comment]
probably because you forgot to add parenthesis after isdigit in the second if condition.

**Comment by padmaja125** [comment]
I tried the same code but not getting the o/p.

**Comment by younghope11** [comment]
> probably because you forgot to add parenthesis after isdigit in the second if condition.

Thanks!!
