### ISSUE TITLE
Cant give my assessment

### ISSUE THREAD

**Issue by SUSMITAM144** [Pierian-Data/Complete-Python-3-Bootcamp#197]
I cant able to type my code in my assessment page

**Comment by CarmenGisa** [comment]
I have the same issue  ...

**Comment by saranie123** [comment]
unable  to type in cells for data object assessment. The double click 'here' does not work.

**Comment by Smritisingh25** [comment]
i am not able to give my assessment. the double click is not working

**Comment by linoyhadad** [comment]
unable to type in cells for data object assessment. The double click 'here' does not work.

 what should i do ?

**Comment by groovy-hungyo** [comment]
same here!
