### ISSUE TITLE
Can't open any topic. What is the problem ? 

### ISSUE THREAD

**Issue by Orshikhbayar** [Pierian-Data/Complete-Python-3-Bootcamp#199]
when i try any topic in Python <> Code part Something went wrong. Reload ? text reveals.

**Comment by Karan2301** [comment]
The Same happening with me 
just came to report the issue and saw you have already done the same....

**Comment by deimar1** [comment]
Same

**Comment by Shubh-199407** [comment]
when i try any topic in Python <> Code part Something went wrong. Reload ? text reveals. >> Same issue for me ,, please help 
!

**Comment by Nashit12** [comment]
can anyone please give me discord link ?

**Comment by Ashwin189** [comment]
can someone give me discord link?
