### ISSUE TITLE
not opening the any file 

### ISSUE THREAD

**Issue by rahulaarya** [Pierian-Data/Complete-Python-3-Bootcamp#206]
![Screenshot (13)](https://user-images.githubusercontent.com/63182767/87439136-78ab9880-c601-11ea-8574-4b3c1c8c8fee.png)

I try to open but its opening , any file with code  please check that images above , please help me to solve the issues .

**Comment by ilkerpel** [comment]
Are you trying to open python notebook with opera web browser ? Please use "Jupyter Notebook" to open it and use the code for studying m8

**Comment by MohammadMojtabaRoshani-TOMaaR** [comment]
i have the same issue but it solved when i use vpn !

**Comment by Pierian-Data** [comment]
Hi Everyone,

I'm not sure how to make it more clear that its not an issue, all you need to do is download the notebooks like we tell you to in the videos.
