### ISSUE TITLE
unable to open any file 

### ISSUE THREAD

**Issue by hasanzaki07** [Pierian-Data/Complete-Python-3-Bootcamp#209]
![Screenshot 2020-07-17 at 3 17 22 AM](https://user-images.githubusercontent.com/54744248/87726192-2bcfe980-c7dc-11ea-8c81-72b91c43c40c.png)

**Comment by FlashGodOfSpeed** [comment]
First open the zip file, then copy the main file inside of that and paste it outside of the zip file

**Comment by SandeepTukkunor** [comment]
You have to extract files from .zip file and then open
