### ISSUE TITLE
Find_33 problem

### ISSUE THREAD

**Issue by AndreasBGJensen** [Pierian-Data/Complete-Python-3-Bootcamp#22]
Hi, everyone. 
Can someone please explain to my what the expression "nums[i:i+2]" do in the find_33 problem. 

The solution is like follows: 
def has_33(nums):
    for i in range(0, len(nums)-1):
      
        # nicer looking alternative in commented code
        #if nums[i] == 3 and nums[i+1] == 3:
    
        if nums[i:i+2] == [3,3]:
            return True  
    
    return False

**Comment by tanishqsol** [comment]
Hii dude,

See if
list1=[1,2,3,4,5,6]

then

list1[1:] = [2,3,4,5,6] (including 1st element)

and

list1[:3] = [1,2,3] (not including 3rd element)

so,

list1[1:3] = [2,3]

similarly in find_33 problem
nums[i:i+2] means any two consecutive numbers.
if i = 1
then i+2 = 3 when compared to the above example i gave.

let me know if this helps.

**Comment by AndreasBGJensen** [comment]
Hi, 

yes that make sense. 

Thanks a lot!

**Comment by Pierian-Data** [comment]
Best place to ask questions is in Udemy QA forums. Thanks!

**Comment by danaconda84** [comment]
Ohhhhh. That makes sense now, thanks for the answer. I was wondering why we would increment by two, but that means up to, but not including the index position.

**Comment by Celebrimbor94** [comment]
> Hi, everyone. Can someone please explain to my what the expression "nums[i:i+2]" do in the find_33 problem.
> 
> The solution is like follows: def has_33(nums): for i in range(0, len(nums)-1):
> 
> ```
>     # nicer looking alternative in commented code
>     #if nums[i] == 3 and nums[i+1] == 3:
> 
>     if nums[i:i+2] == [3,3]:
![Screenshot 2022-06-01 142709](https://user-images.githubusercontent.com/97067557/171367287-2df266d4-580c-4380-974a-f3a26b69bd75.png)

>         return True  
> 
> return False
> ```

it's checking the given input value in the list index with incremented by 2 consecutive and has 3,3 in them serially.
but I'm facing some invalid syntax error in line 3 . please help me solve this situation, I'm following this bootcamp course from Udemy.

**Comment by Celebrimbor94** [comment]
> The code you have is missing the colon you say should be on line three John Owen Salkeld 07384629602 ***@***.*** ***@***.*** Measure with a micrometer, markup with chalk, cut with an axe!
> […](#)
> ________________________________ From: Souvik Pal ***@***.***> Sent: Wednesday, June 1, 2022 9:59:41 AM To: Pierian-Data/Complete-Python-3-Bootcamp ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [Pierian-Data/Complete-Python-3-Bootcamp] Find_33 problem (#22) Hi, everyone. Can someone please explain to my what the expression "nums[i:i+2]" do in the find_33 problem. The solution is like follows: def has_33(nums): for i in range(0, len(nums)-1): # nicer looking alternative in commented code #if nums[i] == 3 and nums[i+1] == 3: if nums[i:i+2] == [3,3]: [Screenshot 2022-06-01 142709]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F97067557%2F171367287-2df266d4-580c-4380-974a-f3a26b69bd75.png&data=05%7C01%7C%7C89f4cf09f53f44b978e108da43ad116c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896707842359176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5sYOhkemVermRloVmY68W8aGlgf750C9ZzTd2e%2FN3KA%3D&reserved=0> return True return False it's checking the given input value in the list index with incremented by 2 consecutive and has 3,3 in them serially. but I'm facing some invalid syntax error in line 3 . please help me solve this situation, I'm following this bootcamp course from Udemy. — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPierian-Data%2FComplete-Python-3-Bootcamp%2Fissues%2F22%23issuecomment-1143325711&data=05%7C01%7C%7C89f4cf09f53f44b978e108da43ad116c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896707842359176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mYYSpTYI8FUNsOIpPf%2Ba4WkoktZ0%2BXhJ40rB7fqLbPQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADUHQAWMZ3I27WYUU53TXEDVM4Q73ANCNFSM4FGHT75A&data=05%7C01%7C%7C89f4cf09f53f44b978e108da43ad116c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896707842359176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kJ0yyCCaDChysPAomKjfNZ%2BwNLM2QRaeeNsGac6njk0%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

thank you, it's solved now \m/
