### ISSUE TITLE
Can't write my Assessment Test

### ISSUE THREAD

**Issue by sakthi1702** [Pierian-Data/Complete-Python-3-Bootcamp#222]
I can't write my assessment test.I have been trying for a while ,Its says double click and you can write you assessment but its not working..

**Comment by poojabhargava30** [comment]
I can't write my assessment test.I have been trying for a while ,Its says double click and you can write you assessment but its not working..

**Comment by LimibabuL** [comment]
i can't write my assessment test. I have been trying for a while , its says double click and you can write but its not working

**Comment by hkahqi** [comment]
HOW?

**Comment by oguzcanaygun** [comment]
i can't write my assessment test. I have been trying for a while , its says double click and you can write but its not working

**Comment by jefhar** [comment]
@oguzcanaygun : Which Jupyter Notebook are you using?

**Comment by oguzcanaygun** [comment]
I COULDNT RE WRITE ON OPERA BROWSER THEN I DOWLANDED ZIP AND EXTRACKED SO I
OPENED IT WITH JUPITER NOTEBOOK FROM ANACONDA I CAN USE IT NOW I FIXED IT
BY USING JUPITOR NOTEBOOK THANKS FOR BACK

Jeff Harris <notifications@github.com>, 30 Eyl 2020 Çar, 20:51 tarihinde
şunu yazdı:

**Comment by defdsdf** [comment]
I can't write any assessment test.

**Comment by EvyMath** [comment]
I also cannot write my assessment, I can not edit the notebook. I am also using jupyter.
