### ISSUE TITLE
I pip installed PyPDF2, but when I try to open it in Jupyter notebook I get error message

### ISSUE THREAD

**Issue by nopressurecooker** [Pierian-Data/Complete-Python-3-Bootcamp#237]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-69e9e6162b4c> in <module>
----> 1 import PyPDF2

ModuleNotFoundError: No module named 'PyPDF2'

**Comment by atena5101** [comment]
https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/issues/237#issue-685722873

**Comment by atena5101** [comment]
> [# 237 (نظر)](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/issues/237#issue-685722873)

**Comment by atena5101** [comment]
> > [# 237 (نظر)](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/issues/237#issue-685722873)

**Comment by atena5101** [comment]
@atena5101

**Comment by atena5101** [comment]
> ModuleNotFoundError Traceback (آخرین تماس آخرین)
> در
> ----> 1 واردات PyPDF2
> 
> ModuleNotFoundError: هیچ ماژولی به نام "PyPDF2" وجود ندارد

**Comment by akash1095** [comment]
it seems you have installed but when you import it, it raises ModuleNot FoundError.

I think the problem is to install, 
kindly check have in installed properly, 
and check the Python environment, because there are chances you may install in different environment.
