### ISSUE TITLE
**kwargs, return in list

### ISSUE THREAD

**Issue by AndreasBGJensen** [Pierian-Data/Complete-Python-3-Bootcamp#24]
Hi everyone 
Can anyone help me to return a list when using **kwargs or *args
I have tryied following:
def myfunc(**kwargs):
   I=list(kwargs)
    for i in I:
        if i %2==0:
            return i

Please help me out:)

**Comment by Pierian-Data** [comment]
Best place to ask questions is in Udemy QA forums. Thanks!
