### ISSUE TITLE
Can't write questions Answer

### ISSUE THREAD

**Issue by Mpatel2121** [Pierian-Data/Complete-Python-3-Bootcamp#253]
Can't write questions answer of Data structure assessments

**Comment by aniketrawat100** [comment]
same

**Comment by jefhar** [comment]
@Mpatel2121 @aniketrawat100 

what did you try? Where did you try it? What did you expect? What was the result?

**Comment by aniketrawat100** [comment]
i was attempting the python test in github i can't write there

**Comment by Pierian-Data** [comment]
Review video lecture on downloading and running jupyter notebooks. Obviously we can not let everyone live-edit the entire course notebooks here on Github, that would not make sense and is not possible. Please refer to the many times this has already been answered in the QA forums.
