### ISSUE TITLE
Changing python directory

### ISSUE THREAD

**Issue by ayeletRamaty** [Pierian-Data/Complete-Python-3-Bootcamp#258]
Hey,

I'm sure this is a small problem, but I struggle it from the beginning of the course and I'll appreciate your help - How can I change a directory when I'm in python?

Thanks for your help!

**Comment by k7r7n** [comment]
just use the cd command

**Comment by walkershashi** [comment]
When you are using python you can change the directory using the chdir() function in the os-module

`import os`
`print(os.getcwd()) # get the current working directory`

`#change to directory one level up`
`os.chdir('..')`
`print(os.getcwd())`

`#change to any directory`
`os.chdir('D:\\StudyMaterials\\Algo') #os.chdir(path)`

Look out for the backslashes in the OS.

**Comment by k7r7n** [comment]
Why do you wanna make a easy thing complex anyway it's your choice so you
do as you desire

**Comment by Pierian-Data** [comment]
This is not an issue with the repo, this seems to be just a general question. Should go in the QA Forums. In the future please do not open issues for general questions like this one, instead post to the QA fourms.
