### ISSUE TITLE
Error with 14_04

### ISSUE THREAD

**Issue by seanmarkin** [Pierian-Data/Complete-Python-3-Bootcamp#28]
When attempting to open: 14-Advanced Python Objects and Data Structures/04-Advanced Dictionaries.ipynb I get an error that says: "Sorry, something went wrong. Reload?"

All other files have opened for me, thus far.

**Comment by pscheid92** [comment]
Hello @seanmarkin,

I tried to open the above mentioned file and everything works correctly.
Could you provide details about your environment, speaking:

- Operating System and Version
- Used Python version
- Used Version of Jupyter
- Used Version of Jupyter-Notebook
- ...
