### ISSUE TITLE
can't edit the test file

### ISSUE THREAD

**Issue by dorfid** [Pierian-Data/Complete-Python-3-Bootcamp#284]
I can't edit and clicking in "HERE" does not react.
the script lines to enter python are not responding as well

**Comment by ranjit7858** [comment]
Hey there that's repository for your course to edit it you have to download
it to your own local repository and there after you can work with it's
files . Yet facing problem then consider watching git tutorial

**Comment by dorfid** [comment]
Thanks for your fast answer,
1 - how do I download? I can't find a download button anywhere around the test file.
2 - why isn't it mentioned in the video #30 in section 3? He claims I can just double click and it would work. That's super confusing.

**Comment by ranjit7858** [comment]
Brother just go with some of git and git hub tutorial on YouTube it will
must help you out with your doubts

**Comment by monjeth** [comment]
on the master view, click the green button "code", and choose download zip. Extract the zipped file to get the .ipynb you are going to work with and you can edit them using Jupyter notebook.

**Comment by dorfid** [comment]
ok thanks @monjeth ! that was very helpful.
I'm there, just still when I type python script in the dedicated lines, it's not running them. when I press enter, an output line does not show up, but a new line opens up in the input textbox.
What can I do?

**Comment by monjeth** [comment]
shift + enter

**Comment by dorfid** [comment]
thanks!
