### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by JAINEELSONI** [Pierian-Data/Complete-Python-3-Bootcamp#291]
not able to write code on github

**Comment by jefhar** [comment]
>not able to write code on github

@JAINEELSONI why would you expect to?

**Comment by JAINEELSONI** [comment]
Ok,so we have to write it on jupiter  notebook !???

**Comment by jefhar** [comment]
Just like it says in lesson 5 of Section 1 of the author's course.

--
Jeffrey Harris.

**Comment by abhifarande** [comment]
while execution of final code,
when we have to make player to choose X or O then we use player_input() function then
it shows this error:
Traceback (most recent call last):
  File "C:\Users\Abhishek\PycharmProjects\firsttry\main.py", line 85, in <module>
    player1_marker,player2_marker=player_input()
TypeError: cannot unpack non-iterable NoneType object
help me

**Comment by Pierian-Data** [comment]
Post to QA Forums, not sure why you would post a GitHub issue for our code when its your .py file that has the error, please review the Course Overview lecture, we talk about how to get help in the course.
