### ISSUE TITLE
Cant edit

### ISSUE THREAD

**Issue by dangelo01** [Pierian-Data/Complete-Python-3-Bootcamp#30]
Trying to do the functional practice exercise but it won't allow me to make any edits or changes in the coding?

**Comment by pscheid92** [comment]
Hello @dangelo01 ,

could you give me the specific file you are talking about?
Are edits or changes not possible in every fields or in specific ones?
Maybe I can reproduce the bug.

**Comment by sanjhipandey** [comment]
https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/blob/master/02-Python%20Statements/07-Statements%20Assessment%20Test.ipynb
 unable to edit 
please help

**Comment by jscooksey** [comment]
You cant edit the GitHub version, you need to do this on your own computer. See section 2 lectures

**Comment by draawblue** [comment]
I am having the same problem. Tried to open in Jupyter Notebook and it won't open. Please, help !!!!

**Comment by Pierian-Data** [comment]
You need to pay questions to the QA forums, not here.
