### ISSUE TITLE
Problem sets needed in each notebook

### ISSUE THREAD

**Issue by mc510** [Pierian-Data/Complete-Python-3-Bootcamp#306]
The lectures are great, but there is no way to learn this stuff without _doing_ it. There needs to be a problem set in each notebook so that students can practice the material as they go. I'm learning about 10% as much from this course as I would if there were practice problem sets in each notebook.

**Comment by VBoB13** [comment]
When I first set of learning from this course, _my perception_ was that there was plenty of practice to go around to the point where I eventually felt I had to pick the challenges that were more challenging for me at the time in order not to spend "too much" time on stuff I already got the gist of, so I am a little surprised that other students find it short on coding challenges...
_**NOTE:**_ There's **NO** such thing as _too much practice_ and you should embrace whatever practice there is available. If you feel they're short on challenges, you can always go on [Hackerrank](https://www.hackerrank.com/) or other similar websites to get a bunch of coding challenges _served on a silver plate_ 😉
