### ISSUE TITLE
Cannot type text

### ISSUE THREAD

**Issue by galdeeb20** [Pierian-Data/Complete-Python-3-Bootcamp#309]
I cannot type text anywhere in the assessment. Please help.

**Comment by jefhar** [comment]
@galdeeb20 did you follow the first unit of the course?

**Comment by galdeeb20** [comment]
> @galdeeb20 did you follow the first unit of the course?

You mean the first section of the course?

**Comment by jefhar** [comment]
Yes. The first portion of the course and the duplicate closed issues where the answer is provided.

**Comment by galdeeb20** [comment]
> Yes. The first portion of the course and the duplicate closed issues where the answer is provided.

ok thanks
