### ISSUE TITLE
Complete-Python-3-Bootcamp

### ISSUE THREAD

**Issue by vnkozolins** [Pierian-Data/Complete-Python-3-Bootcamp#336]
Hey, I can't open any file for Complete-Python-3-Bootcamp course.
says something like that: Sorry, something went wrong, Refresh?

**Comment by adambrosio** [comment]
Same issue.

**Comment by Pierian-Data** [comment]
Just download the notebooks, watch the first few videos of the course if
you are unsure of what I'm talking about
