### ISSUE TITLE
Unable to write code.

### ISSUE THREAD

**Issue by Krishna23-coode** [Pierian-Data/Complete-Python-3-Bootcamp#338]
Could anyone please walk me through the instructions on how to write code?

**Comment by adriananielsen** [comment]
Can´t either

**Comment by adriananielsen** [comment]
Got it! From another question answered months ago: on the master view, click the green button "code", and choose download zip. Extract the zipped file to get the .ipynb you are going to work with and you can edit them using Jupyter notebook. Hope that helps! @Krishna23-coode

**Comment by Pierian-Data** [comment]
Review the video lectures please

**Comment by Krishna23-coode** [comment]
> Got it! From another question answered months ago: on the master view, click the green button "code", and choose download zip. Extract the zipped file to get the .ipynb you are going to work with and you can edit them using Jupyter notebook. Hope that helps! @Krishna23-coode

**Comment by Krishna23-coode** [comment]
@adriananielsen, Thank you so much I will try now.

**Comment by Krishna23-coode** [comment]
@Pierian-Data, thank you.
