### ISSUE TITLE
issues completing the assessment

### ISSUE THREAD

**Issue by ayfix** [Pierian-Data/Complete-Python-3-Bootcamp#339]
how are we suppose to complete the test......
in the course it just asks us to do the questions but the cells attached to those questions doesn't seem to work cauz when i try to write the code it doesn't work,,,

**Comment by kalabtomas** [comment]
Ghf

**Comment by ayfix** [comment]
Which email....????

**Comment by ayfix** [comment]
U mean that I have to download github and then it will work....

**Comment by jefhar** [comment]
It's all explained in section 2 of the course. https://www.udemy.com/complete-python-bootcamp

It's also explained multiple times in the issues https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/issues
