### ISSUE TITLE
 Stuck on Coding Exercise 19: Functions #10: skyline

### ISSUE THREAD

**Issue by Kestasvv** [Pierian-Data/Complete-Python-3-Bootcamp#353]
I am stuck on this, can someone help me figure out code for it

Thank you

**Comment by K-boop-design** [comment]
def myfunc(args):
    tks=args
    e=''
    for x in range(0,len(tks)): #len(agrs)
        if x%2==0:
            e=e+tks[x].lower()
        else:
            e=e+tks[x].upper()
    
    return e

**Comment by mjobusch** [comment]
I am having problems getting the course to acknowledge that my code works -- the long version is that I was hitting around getting this exercise without help, and finally started waving a white flag -- I found this, and was able to get something working without using "enumerate" -- the course exercise didn't count it as correct, so I re-coded it using "enumerate" -- still not grading it as correct, but both versions of my code work in a Jupyter notebook. The in-course message I'm getting says "cannot convert bultin_object_or_method to str implicitly". What is the issue?

**Comment by CrypTO151** [comment]
thank you so much...

**Comment by Aminshr** [comment]
Opted for a direct string manipulation approach instead of **kwargs for simplicity. Please review.

def myfunc(s):
    # Initialize an empty string to store the result
    result = ""
    # Iterate over the string with index and character
    for index, char in enumerate(s):
        # Check if the index is even
        if index % 2 == 0:
            result += char.upper()  # Add uppercase if index is even
        else:
            result += char.lower()  # Add lowercase if index is odd
    return result
