### ISSUE TITLE
One notebook from Working With Images is not opening

### ISSUE THREAD

**Issue by Divyu77** [Pierian-Data/Complete-Python-3-Bootcamp#373]
From Working with images I am not able to get anything on Overview-of-Working-with-Images.ipynb. Whenever I open this file it shows to me Something went wrong.

**Comment by zahidford** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Divyu77 ***@***.***>
Sent: Sunday, July 18, 2021 1:02:29 PM
To: Pierian-Data/Complete-Python-3-Bootcamp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pierian-Data/Complete-Python-3-Bootcamp] One notebook from Working With Images is not opening (#373)


From Working with images I am not able to get anything on Overview-of-Working-with-Images.ipynb. Whenever I open this file it shows to me Something went wrong.
