### ISSUE TITLE
Coding Exercise 9: File I/O

### ISSUE THREAD

**Issue by kiran-theja** [Pierian-Data/Complete-Python-3-Bootcamp#374]
I am unable to answer the exercise. What is the correct solution?

**Comment by VikasNagaraj** [comment]
Hi Kiran,

Please create a .txt file first and follow the example in the exercise, it will definatly work.

**Comment by kiran-theja** [comment]
Still not getting the solution. Please write the correct solution here

**Comment by 145195** [comment]
Mr.Kiran,
the way you said is correct there is a same issue for me.
