### ISSUE TITLE
in my jupyter notebook i can't copy and paste

### ISSUE THREAD

**Issue by tysons96** [Pierian-Data/Complete-Python-3-Bootcamp#38]

**Comment by rkritika1508** [comment]
You can easily copy and paste code in jupyter notebook. Just select the coding area of cell and press Ctrl+V.

**Comment by psgareja** [comment]
Re install anaconda

**Comment by abrahamguta** [comment]
jupyter notebook.

**Comment by Mitra-babu** [comment]
1. Restart Jupyter notebook
2. Select 'nontrust' to 'trusted' from the top right corner of the python file
3. refresh it
