### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by Samchegz** [Pierian-Data/Complete-Python-3-Bootcamp#39]
I like to confirm if i can download the video to enable me watch the video training without using my data

**Comment by psgareja** [comment]
Yes you can download from Udemy app in ur mobile phone ..or second opinion
is enable any video downloader in crome browser , so u can easily download
from there

**Comment by UncleCyber** [comment]
There is an option on Github to where you can fork it to your profile.it
should be right on top of Download zip or clone download on Github

**Comment by vivek15028** [comment]
How I can download fnq lecture Notebook?
