### ISSUE TITLE
why am i not able to type my code in place provided

### ISSUE THREAD

**Issue by SankaSanjana** [Pierian-Data/Complete-Python-3-Bootcamp#404]

**Comment by jefhar** [comment]
@SankaSanjana Maybe because you didn't complete the section of the class that gives you the exact instructions?

**Comment by Ppravin28** [comment]
Hope you're now able to write those codes. if not then i can help you with that.

**Comment by SankaSanjana** [comment]
Can u please guide and help me

**Comment by Ppravin28** [comment]
Sure. There is option in code to download it in zip file . Download it then
you can run it in your jupyter network .

**Comment by Pierian-Data** [comment]
Please don't skip the setup and install video lectures! Not sure why you are for help/guidance here, when we literally show how to do it in the video course. Also we make it pretty clear that the Q&A forum inside the course is the best place to get help if you did need assistance. Your question has already been answered there.
