### ISSUE TITLE
Please include Links to next Github Pages

### ISSUE THREAD

**Issue by RobinBijo** [Pierian-Data/Complete-Python-3-Bootcamp#405]
Please include the next page links below each page.That is in [Pierian-Data/Complete-Python-3-Bootcamp/00-Python Object and Data Structure Basics/02-Strings.ipynb](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/blob/master/00-Python%20Object%20and%20Data%20Structure%20Basics/02-Strings.ipynb) last word is Next Up: Lists! So please provide the link for Lists too just below it.Makes it easy to navigate,as coming out and going to the next file is pretty difficult @Pierian-Data @TiVentures

**Comment by bhumi-cka** [comment]
Just download the complete zip folder. Makes everything a lot easier.

**Comment by RobinBijo** [comment]
@bhumi-cka Downloading the entire zip folder doesn't work.There is a lot of data but useful one.My storage space is gonna go.That's why. A huge shoutout to _@Pierian-Data_ and **@jmportilla** for creating such a large repository

**Comment by Pierian-Data** [comment]
The repo zip is only 25MB, downloading Python and a text editor would be much, much more. Also why is the current structure so difficult? You would just need to click the back button once to see the next notebook as everything is in order.
