### ISSUE TITLE
Tuple Unpacking

### ISSUE THREAD

**Issue by cbandss** [Pierian-Data/Complete-Python-3-Bootcamp#414]
While working on the tuple unpacking section in the methods and functions the part about the employee of the month, when it was done and I ran the code it came up as an error saying "too many values to unpack (expected 2)" even when i tried to copy and paste the example from the notebook it still would come up with the same error (note: it gives me the error when i try to run the  answer, the actual: employee_check(work_hours)
![110E5E29-4161-456E-8F04-013E49BC604F](https://user-images.githubusercontent.com/99369625/153309380-ba5c4081-e64a-48fd-ab88-c5edb6124dc8.png)

**Comment by someone20dz** [comment]
Try reset the kernel

**Comment by cbandss** [comment]
copy and pasted and all fixed. Thanks!!
