### ISSUE TITLE
Audio Problem

### ISSUE THREAD

**Issue by Chrislalika** [Pierian-Data/Complete-Python-3-Bootcamp#416]
To whom it may concern
I am a new student in the Python course, so I am experiencing the challenge of audio while I am listening to podcasts.
Kindly I would like to request technical support on this matter.

Regards
Chris

**Comment by jmportilla** [comment]
Contact ***@***.***

**Comment by Pierian-Data** [comment]
This is a course, not a podcast. Contact Udemy Support, I think its an issue with them, not an issue here with the notebooks.
