### ISSUE TITLE
The Videos do not load

### ISSUE THREAD

**Issue by iamveryhype** [Pierian-Data/Complete-Python-3-Bootcamp#438]
I try to open the course on Udemy, however the videos do not load at all
<img width="1242" alt="Screenshot 2022-05-06 at 04 09 16" src="https://user-images.githubusercontent.com/105026241/167050651-402589ee-de67-420e-9ed4-71ac081fa27a.png">

**Comment by jmportilla** [comment]
Email udemy support

**Comment by iamveryhype** [comment]
Already did, they said they are experiencing a high volume of support tickets and responses might be delayed.They sent a list of things to do, which did not help.

**Comment by iamveryhype** [comment]
> I try to open the course on Udemy, however the videos do not load at all <img alt="Screenshot 2022-05-06 at 04 09 16" width="1242" src="https://user-images.githubusercontent.com/105026241/167050651-402589ee-de67-420e-9ed4-71ac081fa27a.png">
Only this course is not working all the other seem to be working all right.

**Comment by Pierian-Data** [comment]
Sorry, it's an issue on udemy, not our fault and there isn't anything we
can do from our end. We have the most popular course on udemy, so it's an
issue, I don't know why they don't provide more bandwidth for us

**Comment by mayesch** [comment]
I was having the same issue the other night with Safari. I switched to Brave and it started working normally.

Thanks

Chuck Mayes
***@***.***
803-315-4022 - Cell
