### ISSUE TITLE
Blank page after leaving an exercise.

### ISSUE THREAD

**Issue by iamveryhype** [Pierian-Data/Complete-Python-3-Bootcamp#439]
After leaving an exercise skyline and coming back to it, it shows  a blank page.
<img width="1097" alt="Screenshot 2022-05-07 at 18 16 16" src="https://user-images.githubusercontent.com/105026241/167260514-25572e1f-155b-44e7-953b-43470b9ddaaa.png">
<img width="422" alt="Screenshot 2022-05-07 at 18 16 05" src="https://user-images.githubusercontent.com/105026241/167260506-7f5728a8-3826-4042-8c75-756d117e0532.png">

**Comment by iamveryhype** [comment]
Here is the console javascript of the error
<img width="554" alt="Screenshot 2022-05-09 at 01 19 28" src="https://user-images.githubusercontent.com/105026241/167444803-1c0e4035-17ee-48dd-9b56-b37233387edc.png">
<img width="553" alt="Screenshot 2022-05-09 at 01 19 47" src="https://user-images.githubusercontent.com/105026241/167444815-e643a2e8-b79a-4af3-8d21-148efb3064de.png">

**Comment by Pierian-Data** [comment]
Hi @iamveryhype , 

I'm sorry about the issues you are experiencing, but please understand, we don't control the Udemy website in any way, there isn't anything we can do with this information on our end, we literally just upload the content. This is the kind of information Udemy Support needs, Udemy is the only one that can fix this issue. Again, I'm sorry for the trouble you are having, but we can't do anything from our end. We've already opened up a support ticket with Udemy Instructor support and they tell us that the student needs to directly reach out.
