### ISSUE TITLE
Course material

### ISSUE THREAD

**Issue by aravindjaga18** [Pierian-Data/Complete-Python-3-Bootcamp#470]

**Comment by MARCIALBRO** [comment]
How can i download the course material???
please tell

**Comment by aravindjaga18** [comment]
> How can i download the course material???
> please tell

You want material ?

**Comment by aravindjaga18** [comment]
Msg me on WhatsApp +919384660970

**Comment by jmportilla** [comment]
We show how to download the notebooks in the first few lectures
