### ISSUE TITLE
milestone2 :AttributeError: 'Deck' object has no attribute 'deck'

### ISSUE THREAD

**Issue by nishreenk** [Pierian-Data/Complete-Python-3-Bootcamp#52]
Cant understand why am I getting this error?
Thanks for your help.

class Deck:
    def __init__self():
        self.deck =[]
        for i in shapes:
            for j in rank:
                self.deck.append(card(rank,shapes))             
           
    def __str__(self):
        return f'The CardDeck is {self.deck}'
    
    def deal(self):
        random.shuffle(self.deck)
    
    def deal(self):
        self.deck.pop()

test_deck = Deck()
print(test_deck)

**Comment by mahima5598** [comment]
def __init__self() is wrong it should be def __init__(self)

**Comment by hiankitm** [comment]
If @nishreenk you can tell what error it is then i may know what to do

**Comment by isha2604** [comment]
AttributeError: 'Deck' object has no attribute 'all_card'
I am getting this error when I try to run the self.all_card.append function .

**Comment by harshitbansal184507** [comment]
33333es58,4433, ,

**Comment by Tesla357** [comment]
Unsubscribe

On 15 May 2022, at 6:24 pm, harshitbansal184507 ***@***.***> wrote:

﻿

33333es58,4433, ,
