### ISSUE TITLE
Else going in loop for false condition

### ISSUE THREAD

**Issue by Heart-Beat** [Pierian-Data/Complete-Python-3-Bootcamp#53]

**Comment by Heart-Beat** [comment]
In my code I am trying to calculate area of a circle if user enters Struct = 1 and ops = 2.
If user enters wrong input then will be asked again till he enters correct value.

This code is working fine for if user enters correct value what is expected but if he enters wrong input then it's going in infinite loop.

Not sure how to resolve.
[Python_Code.txt](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/files/2952436/Python_Code.txt)

**Comment by Heart-Beat** [comment]
Few screenshots which might help to understand my issue.
![Python_Loop_Error](https://user-images.githubusercontent.com/25197995/54128573-654b5480-4432-11e9-839a-fddb1ac8e744.PNG)
![Python_True](https://user-images.githubusercontent.com/25197995/54128574-654b5480-4432-11e9-92f2-65ca080172e8.PNG)

**Comment by Pthakur17** [comment]
You didn't break the while loop

**Comment by Heart-Beat** [comment]
Thanks for responding.

I guess it not required as I tried same scenario with while loop and it's working perfectly fine. Attached is the screenshot.

![Python_Loop_Error_2](https://user-images.githubusercontent.com/25197995/54198165-d0a52d00-44eb-11e9-9329-9d1edf56145c.PNG)
Still if you think there is a correction needed can you please help me with the corrected code.

I need it as I am very new to Python and is difficult to understand all tricks.

Appreciate you help.
