### ISSUE TITLE
Can't' access the exercises

### ISSUE THREAD

**Issue by HKayumba** [Pierian-Data/Complete-Python-3-Bootcamp#536]
![Screenshot (134)](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/assets/84237371/68682b41-6013-45b6-be6a-51f85af8933b)
I can't access the exercises about functions.

**Comment by jefhar** [comment]
@HKayumba Did you get to chapter 6 of the course yet?

**Comment by Pierian-Data** [comment]
please download the zip from the Udemy course
