### ISSUE TITLE
i need new line in this code

### ISSUE THREAD

**Issue by madhumitan** [Pierian-Data/Complete-Python-3-Bootcamp#55]
%%writefile mylife.txt
hello ord 
hello cazy
hello weezy & zak 
hello hemy & max
mylife=open('mylife.txt')
mylife.read()
mylife.seek(0)
mylife.read()
contents=mylife.seek(0)
mylife.readlines()
['hello ord \n', 'hello cazy\n', 'hello weezy & zak \n', 'hello hemy & max \n']
#i need above lines in new lines

**Comment by bh72** [comment]
#Hello, I check your code and it seems that there is something wrong with your text by using "&" sign, which cause that they don't come in new lines...
#change the "&" sign to "and", see the result, 
#Good luck

**Comment by madhumitan** [comment]
#thank you so much,its working
#i understood my mistake
