### ISSUE TITLE
exercises palimdron

### ISSUE THREAD

**Issue by Konrad123456** [Pierian-Data/Complete-Python-3-Bootcamp#57]
Write a Python function that checks whether a passed string is palindrome or not.

Note: A palindrome is word, phrase, or sequence that reads the same backward as forward, e.g., madam or nurses run.

I have problem. When my string have more than 1 part "Nurses run", y take only first part "Nurses". I don't know why. Can someone help me?

def palindrom(string):
    word = string.split(" ")
    y = ""
    for z in word:
        y += z
        if y.lower() == y.lower()[::-1]:
            print(word)
            print(y)
            return f" True word = {y.lower()}, palindrom = {y.lower()[::-1]}"
        else:
            print(word)
            print(y)
            return f"False word = {y.lower()}, palindrom = {y.lower()[::-1]}"

**Comment by carlcx52a** [comment]
Hello,

When you call your function with argument 'Nurses run', word will be a list - ['Nurses', 'Run'], when the loops starts, initially z = 'Nurses', so y = 'Nurses', I think this is which you meant 'it took only first part'. When it loops second time(as there are 2 items in word list), then y='Nurses' + 'run' = 'Nursesrun', then y has both parts of your string, and it will return true this time. Hope this helps and let me know if you have any questions.

**Comment by Konrad123456** [comment]
![image](https://user-images.githubusercontent.com/48552706/55099373-de4bdc80-50bf-11e9-9787-91b4c226281b.png)

I don't know why the function's given me False when I put "Nurses run". I don't know why the loop did't go second time.

**Comment by carlcx52a** [comment]
As you're using return in the function, it will end the current scope and the second loop never comes. So when it loops for the first time, just like I mentioned in the previous comment, it will return false. Try replacing both return with print. Then it will return true in the second time of loop. Btw, unless you want to practice using loop, you can just take out the spaces from your string and do the check, or concatenate the string in word list after you split them.

**Comment by Konrad123456** [comment]
Ok, I understand :) thank you very much for your help

**Comment by Raghu0203** [comment]
``def check(text):
    s=text.lower()
    a=s.split()
    tt=""
    for item in a
        tt+=item
    return tt==tt[::-1]
     
    ### just an other beginner's code to :-)
