### ISSUE TITLE
Cells are not writeable for me

### ISSUE THREAD

**Issue by hashtarkhani** [Pierian-Data/Complete-Python-3-Bootcamp#59]
Hi, I don't know why I can't type in cells.
I use chrome.
thanks

**Comment by melissak10** [comment]
I'm not sure if this helps but I had a similar issue with taking the first assessment so I created a GitHub account (not 100% sure if this is necessary) and then I could edit the file. However, to take the assessment, I downloaded the files navigated through Jupyter to the first assessment to take the test.

**Comment by Unknownikov** [comment]
Is there another solution for that? Same issue here.

**Comment by nelsond3381** [comment]
can you stop with all these notifications

**Comment by ML33M** [comment]
Yes please stop the notifications

**Comment by benyizhang** [comment]
I received nearly 50 Email with one minute 🙁.

________________________________
发件人: nelsond3381 <notifications@github.com>
发送时间: 2020年4月20日 20:44
收件人: Pierian-Data/Complete-Python-3-Bootcamp <Complete-Python-3-Bootcamp@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Pierian-Data/Complete-Python-3-Bootcamp] Cells are not writeable for me (#59)


can you stop with all these notifications

**Comment by Merlin1908** [comment]
Happy 420 y’all

**Comment by xzax** [comment]
Cheers 123

**Comment by Mehmetdmr60** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:SimSun;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:"Yu Gothic";
	panose-1:2 11 4 0 0 0 0 0 0 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Segoe UI Emoji";
	panose-1:2 11 5 2 4 2 4 2 2 3;}
@font-face
	{font-family:"\@SimSun";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"\@Yu Gothic";
	panose-1:2 11 4 0 0 0 0 0 0 0;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
