### ISSUE TITLE
Error Message when I try to open notebooks

### ISSUE THREAD

**Issue by em1nel1** [Pierian-Data/Complete-Python-3-Bootcamp#598]
I get an error message when I try to open the notebooks

**Comment by Dibyani25** [comment]
I'm also getting the same message.

**Comment by Soham2500** [comment]
same

**Comment by avivov** [comment]
same

**Comment by jefhar** [comment]
@em1nel1 @Dibyani25 @Soham2500 @avivov
Can we assume you have **not** been through section 2 of the Udemy course that gives full instructions on how to install the tools, and download and open the notebooks?

**Comment by Pierian-Data** [comment]
Hi,
Please remember to watch the video lecture where we show how to download the notebooks locally, thanks!

**Comment by Dibyani25** [comment]
My jupyter notebook is not running the cell, showing "Cell not executed due to pending input". How to fix it?
![Screenshot 2024-05-25 205046](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/assets/158053568/6f6005d4-abfa-463f-ad03-88ca5cb12f77)
