### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Sowmyareddy2583** [Pierian-Data/Complete-Python-3-Bootcamp#601]
Unable to open python notebook

**Comment by Sowmyareddy2583** [comment]
we can't download every recording if we have github we can come and refer what ever we need so please go through this and why is it showing error occured

**Comment by Pierian-Data** [comment]
Hi,
I am not talking about download videos, please re-watch lecture 9, we show how to download the notebooks to your computer. Please post further questions to the QA forums inside the course (but also please make sure to search for previous QA posts on this, as we have detailed instructions on how to download and run these notebooks locally, as well as in the FAQ lecture).
