### ISSUE TITLE
Goin in loop

### ISSUE THREAD

**Issue by rahulsm27** [Pierian-Data/Complete-Python-3-Bootcamp#72]
below line of code is goin in loop...what mistake i am makingg    
def player_input():
    
    player1 = ''
    player2 = ''
    
    while (player1 != 'X' or player1 != 'O'):
        player1 = input('Please pick a marker X or O')
            
    if player1 == 'X':
        player2 == 'O'
    else :
        player2 == 'X'

**Comment by malfoy1995** [comment]
The OR operator is the main reason behind this infinite loop because, what
ever operation you are doing inside the loop with X gets satisfied in the
condition checking area of loop and hence never gets out of the loop
