### ISSUE TITLE
03-Function Practice Exercises PAPER DOLL

### ISSUE THREAD

**Issue by tncpanel** [Pierian-Data/Complete-Python-3-Bootcamp#74]
Is paper_doll('**Mississippi**') this should be paper_doll('**Missippi**')?

**Comment by rowena-c** [comment]
hi are these notebooks

**Comment by kyrptokun** [comment]
Good

**Comment by ahmed141** [comment]
> hi are these notebooks

Yes, these are python notebooks. You can open them by installing Jupyter Notebook.

**Comment by BalajiTechs** [comment]
As per statement in practice 
PAPER DOLL: Given a string, return a string where for every character in the original there are three characters
paper_doll('Hello') --> 'HHHeeellllllooo'
**_paper_doll('Mississippi') --> 'MMMiiissssssiiippppppiii'_**

Highlighted needs to be corrected to 
_**paper_doll('Mississippi') --> 'MMMiiissssssiiissssssiiippppppiii'**_
