### ISSUE TITLE
Cant Chose 'o' in milestone project 1

### ISSUE THREAD

**Issue by siddharthdullu** [Pierian-Data/Complete-Python-3-Bootcamp#81]
from IPython.display import clear_output
def display_board(board):
    clear_output()
    print(board[7]+'|'+board[8]+'|'+board[9])
    print(board[4]+'|'+board[5]+'|'+board[6])
    print(board[1]+'|'+board[2]+'|'+board[3])
     
    
def player_input():
    marker = ''
    
    
    while not (marker=='X' or marker=='0'):
        marker = input('Player1 : Do you want to be X or O').upper()
    
    if marker == 'X':
        return ('X','O')
    else:
        if marker =='O':
            return ('O','X')

def place_marker(board,marker,position):
    
    board[position]= marker

def win_check(board, mark):
    
       return ((board[7] == mark and board[8] == mark and board[9] == mark) or # across the top
    (board[4] == mark and board[5] == mark and board[6] == mark) or # across the middle
    (board[1] == mark and board[2] == mark and board[3] == mark) or # across the bottom
    (board[7] == mark and board[4] == mark and board[1] == mark) or # down the middle
    (board[8] == mark and board[5] == mark and board[2] == mark) or # down the middle
    (board[9] == mark and board[6] == mark and board[3] == mark) or # down the right side
    (board[7] == mark and board[5] == mark and board[3] == mark) or # diagonal
    (board[9] == mark and board[5] == mark and board[1] == mark))
        
import random 

def choose_first():
    
    flip = random.randint(0,1)
    
    if flip==0:
        return 'Player1'
    else:
        return 'Player2'
        
def space_check(board,position):
    
    return board[position]== ' '
    
def full_board_check(board):
    
    for i in range(1,10):
        if space_check(board,i):
            return False
    
    return True

def player_choice(board):
    
    position = 0
    
    while position not in range(1,10) or not space_check(board,position):
        position=int(input('choose a position: (1-9) '))
    return position

def replay():
    
    choice = input('Play Again? Enter Yes or No')
    
    return choice== 'Yes'.lower()

print('Welcome To Tic Tac Toe!')

while True:
    
    the_board= [' ']*10
    
    player1_marker,player2_marker=player_input()
    
    turn = choose_first()
    print(turn+'will go first!')
    
    play_game= input('Ready to play? y or n?')
    
    if play_game== 'y':
        game_on = True
    else:
        game_on = False
        
    while game_on:
        
        if turn == 'Player 1':
            
            display_board(the_board)
            
            position = player_choice(the_board)
            
            place_marker(the_board,player1_marker,position)
            
            if win_check(the_board,player1_marker):
                display_board(the_board)
                print('Player 1 Has Won')
                game_on = False
            else:
                if full_board_check(the_board):
                    display_board(the_board)
                    print('Tie Game!!')
                    break
                else:
                    turn = 'Player 2'
                
                        
        else:
            display_board(the_board)
            
            position = player_choice(the_board)
            
            place_marker(the_board,player2_marker,position)
            
            if win_check(the_board,player2_marker):
                display_board(the_board)
                print('Player 2 Has Won')
                game_on = False
            else:
                if full_board_check(the_board):
                    display_board(the_board)
                    print('Tie Game!!')
                    break
                else:
                    turn = 'Player 1'
            
    if not replay():
        break

cant chose o in milestone project 1 please help, point out my mistake

**Comment by Muhammad0312** [comment]
you have typed zero instead of o

**Comment by avadhootkulkarni** [comment]
The error is caused by **_while not (marker=='X' or marker=='0')_**

It should be **_while not (marker=='X' or marker=='O')_**

You have assigned '0' instead of 'O'
