### ISSUE TITLE
Hello im having problem to fix my code.

### ISSUE THREAD

**Issue by Garoshig** [Pierian-Data/Complete-Python-3-Bootcamp#82]
/*
 Make sure and use the required functions as indicated in the instructions for this program!  Use value returning functions where asked for ( this is REQUIRED - I want to make sure people understand value returning functions, void functions are overused and are more procedural, I want to get away from that).  NO GLOBALS and unless specifically asked for (THEY ARE NOT AND WILL NOT BE ASKED FOR)  and  no void functions (unless specifically asked for which I don't think they are). 
 */

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

string getPlayerChoice();
double getComputerChoice();
int computerChoice;
char  userChoice;
string result;

string getComputerChoice ( string computerChoice)
{
    double computer;
    computer = rand() % 3 + 1;
    
if (computer ==1)
{
    computerChoice = getComputerChoice();
    return computerChoice;
}
    else if (computer == 2)
    {
       computerChoice = getComputerChoice();
        return computerChoice;
        
    }
    else
    {
        computerChoice = getComputerChoice();
        return computerChoice;
    }
}
    string getPlayerChoice(string userChoice)
    
{
    double user;
    cin>>user;
     if (user <1 || user >3)
     {
         cout<<"Invalid Selection. Try again.";
         system("PAUSE");
         return 0;
     }
    else if (user == 1)
    {
        userChoice = getPlayerChoice();
        return userChoice;
    }
    else if ( user == 2)
    {
        userChoice = getPlayerChoice();
        return userChoice;
    }
    else
    {
        userChoice = getPlayerChoice();
        return userChoice;
    }
}
string DetermineWinner (string userChoice, string computerChoice, string result)
{
if (computerChoice == userChoice)
{
    result = "It's TIE!";
    return result;
}
    else if (userChoice =="Rock")
    {
        if (computerChoice == "Scissor")
        {
            result = "You WIN!";
            return result;
        }
    else
    {
        result = "You WIN!";
        return result;
    }
        
    }
    else if (userChoice == "Rock")
    {
        if (computerChoice == "Paper")
        {
            result = "Sorry you LOSE.";
            return result;
        }
        else
        {
            result = "You WIN!";
            return result;
        }
    }
    else
    {
        if(computerChoice == "Paper")
        {
            result = "You WIN!";
            return result;
        }
        else
        {
            result = "Sorry you LOSE.";
            return result;
        }
        
        
    }

}
int main ()
{
    string Rock;
    string Paper;
    string Scissors;
    
    
    srand ((unsigned int)time(NULL));
    
    
    cout<<"ROCK PAPER SCISSORS MENU"<<endl;
    cout<<"------------------------"<<endl;
    cout<<"p) PLayGame "<<endl;
    cout<<"q) Quit "<<endl;
    cout<<"Please enter your chose : ";
    cin>>userChoice;
    
    if (userChoice == 'p' || userChoice == 'P')
    {
        computerChoice = getComputerChoice();
        
    }
    else if (userChoice != 'q' || userChoice != 'Q')
    {
        cout<<"You have chosen to quit the program. Thank you for using the program!";
    }

    cout<<"Rock, Paper,Scissors?"<<endl;
    cout<<"1) Rock "<<endl;
    cout<<"2) Paper "<<endl;
    cout<<"3) Scissors "<<endl;
    
    string userChoice, computerChoice, result;
    
    getPlayerChoice(userChoice);
    getComputerChoice(computerChoice);
    DetermineWinner(userChoice, computerChoice, result);
    
    cout<<"You chose : "<<userChoice<<endl;
    cout<<"The computer chose : "<<computerChoice<<endl;
    cout<<result<<endl;
    system("PAUSE");
    return 0;
    
}

// MUCH APPRECIATE THANK YOU !

**Comment by medawarb** [comment]
Hi, can you unsubscribe me?

Bassem Medawar

**Comment by Garoshig** [comment]
what do you mean ? i didn't subscribe  someone to UNSUBSCRIBE!.
