### ISSUE TITLE
When I type in the code it just shows: In[*].

### ISSUE THREAD

**Issue by JackBowness** [Pierian-Data/Complete-Python-3-Bootcamp#86]
When I first went on to Jupyter Notebook it worked fine, but after a few lessons of using it the code would not work at all and it would show: In[*]. No matter what code I put in it just wouldn't work. I tried restarting the Kernel, deleting other files, everything! I eventually went on to Jupyter lab but it did the exact same thing that Jupyter Notebook did. Can someone please help me out with this?

**Comment by PSboi** [comment]
In[*] this means that your code is running in compiler. so  wait for some time and you will see result. or either try to write only one line of code in one shell
