### ISSUE TITLE
python 3.7.4 syntax error

### ISSUE THREAD

**Issue by anki2dev** [Pierian-Data/Complete-Python-3-Bootcamp#91]
####while running this code in python shell, getting invalid syntax in the second line of code
class line:
             def__init__(self,coor1,coor2):      ### invalid syntax ###
                      self.coor1=coor1
                      self.coor2=coor2
             def distance (self):
                       x1,y1=self.coor1
                       x2,y2=self.coor2

                      return ((x2-x1)**2 + (y2-y1)**2)**0.5
            def slope (self);
                     x1,y1=self.coor1
                     x2,y2=self.coor2

        return (y2-y1)(x2-x1)
coor1=(3,2)
coor2=(8,10)

myline= line(coor1,coor2)

**Comment by anki2dev** [comment]
![Capture](https://user-images.githubusercontent.com/48417200/66653368-7755d580-ec55-11e9-9eec-88f05b60e481.PNG)

such type of error

**Comment by mananmdesai** [comment]
Compile without the space in function 'slope':
'slope (self)'
'slope(self)'

---
Regards,
MD
