### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by JaJaQ** [Pierian-Data/Complete-Python-3-Bootcamp#93]
Hi, I encountered this issue when I try to pass in a list object in a function inside another function. I have a game_on() function with all the main code. There I had a pre-defined value(hand) func to calculate hand value comparing to 21. but when I try to pass in player_hand, this error keeps pop out but when I wrote it eslewhere. it is fine. Please see attached screenshot:
![Error 1](https://user-images.githubusercontent.com/56665268/66976609-7ca98a80-f070-11e9-9de7-53d8ea5f5cfe.png)

If I try to do the same at a new block, there will be no message as 'str' object is not callable. It would work as it should be.

Could you advise on the issue?

Thanks!

**Comment by well-established-rufus22** [comment]
https://getchremy.github.io/on3J_lpiEw/
