### ISSUE TITLE
program to find prime numbers

### ISSUE THREAD

**Issue by samarthp6** [Pierian-Data/Complete-Python-3-Bootcamp#95]
import math

def is_prime2(num):
    '''
    Better method of checking for primes. 
    '''
    if num % 2 == 0 and num > 2: 
        return False
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

is the program correct, because for ever number it just returns true

**Comment by ofirlevy6658** [comment]
yea its woking

**Comment by nikhilrana015** [comment]
Indentation Error. Correct One 
import math

def is_prime2(num):

    if num % 2 == 0 and num > 2:
        return False
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

**Comment by jfdahl** [comment]
The is_prime2 function defined below incorrectly responds that 1 is prime. In your lecture, you state: "By convention 0 and 1 are not prime."

```
import math

def is_prime2(num):
    '''
    Better method of checking for primes. 
    '''
    if num % 2 == 0 and num > 2: 
        return False
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True
```

**Comment by longwuyuan** [comment]
i thought that num being a string has to be converted to int before doing a sqrt on it

**Comment by ALLAN001-AM** [comment]
should i change num to be a string first ?

**Comment by ALLAN001-AM** [comment]
Should I change num to be a int first

**Comment by jfdahl** [comment]
> i thought that num being a string has to be converted to int before doing a sqrt on it

As I read the function definition, `num` should be passed in as a number. By convention, it should be an `int`, but I would not expect `num` to be a `str` in the context of this function. In the example that is used, it is passed an `int`:

`is_prime2(18)`

**Comment by LeeZee1** [comment]
Can someone please help me with my code to write function that returns the count of prime numbers up to and including the input number? 

```
def count_primes(num):
    start = 2
    end = 1000
    count=0
    for num in range(start, end + 1): 
   # If num is divisible by any number between 2 and val, besides itself and 1 
   # it is not prime.  
        for x in range(2, num):
            if num > 1 and num%num==0 and num%1==0 and num%x!=0:
                count+=1
                return count
```

**Comment by rajsardhara** [comment]
Try this:

def count_primes(num):
primes = []
start = 2
counter = 0
for i in range(start, num + 1):
if i > 1:
for n in range(2, i):
if (i % n) == 0:
break
else:
primes.append(i)
counter+=1
print(primes)
print("Total prime numbers: ", counter)

Thanks & Regard,

**Comment by rajsardhara** [comment]
Try this:

```
def count_primes(num):
    primes = []
    start = 2
    counter = 0
    for i in range(start, num + 1):
        if i > 1:
            for n in range(2, i):
                if (i % n) == 0:
                    break
            else:
                primes.append(i)
                counter+=1
    print(primes)
    print("Total prime numbers: ", counter)
```

**Comment by LeeZee1** [comment]
Rajsardhara,
Thank you, I got it.
However, can you please tell me why the 'else:' in line 10 has to be indented to be in line with the 'for' statement in line 7?

I thought it should be in line with the 'if' statement in line 8.

**Comment by rajsardhara** [comment]
In Python you can use **else** not just with **if** but also with **loop**, Let me explain you in a theorical way from my notes:

Else statement will execute only if the **loop** is executed without any interruption, For example, if you've used **Break** function in your loop and if it'll break the loop then **else** block will not execute. But if loop executes without break then it'll execute **else** block also, Here is a simple example of it:

```
for i in 'Hello World': ##Run with space and without space
    if i == ' ':
        break
    print(i, end=' ')
else:
    print('\n\n\nI am else - block')
```
I hope this will give you clear picture of **else** with **loop** you can also use **else** with **while** loop.

**Comment by LeeZee1** [comment]
rajsardhara, thanks.
But isn't there a break in the for loop in line three of your code?  If so, why would 'else' statement be able to execute?

Thanks in advance.

**Comment by rajsardhara** [comment]
@LeeZee1 Please read Definition I posted You'll understand use case scenario of **else** with **loop**

**Comment by LeeZee1** [comment]
Rajsardhara,
Thank you.  So, I see how if the 'if' statement condition is met then break is executed and then the 'else' statement does not execute.

But, I'm wondering why the code when it looks like the following doesn't work and instead gives an error:

```
for i in 'Hello World': ##Run with space and without space
    if i == ' ':
        break
    print(i, end=' ')
    else:
        print('\n\n\nI am else - block')
```
it gives error:
 File "<ipython-input-15-8b81b20e1ad8>", line 5
    else:
       ^
SyntaxError: invalid syntax

**Comment by rajsardhara** [comment]
Because your code is incorrect here is correct one, just be careful with indentation:
```
for i in 'Hello World':
    if i == ' ':
        break
        print(i, end=' ')
    else:
        print('I am else - block')
```

**Comment by LeeZee1** [comment]
Ok, thank you.  I changed indentation and it works.

But if I just want the count of primes up to and including 100, the following function returns '1059' instead of '25' when you run: 

 ```
# Check
count_primes(100)
```

```
def count_primes(num):
    start = 2
    end = 100
    counter=0
    for i in range(start, end + 1):   
        if i > 1:
            for x in range(2, i): 
                if i%x==0:
                    break
                else:
                    counter+=1
    return counter
```

**Comment by dhanushMindia** [comment]
num = int(input("Enter a number: ")) #prime numbers are greater than 1
if num > 1: # check for factors for i in range(2,num): if (num % i) == 0:
print(num,"is not a prime number") print(i,"times",num//i,"is",num) break
else: print(num,"is a prime number") # if input number is less than # or
equal to 1, it is not prime else: print(num,"is not a prime number")
Works flawlessly
M Dhanush
